version: "3.8"

services:
  server:
    build: .
    command: python3 run_server.py
    cap_add:
      - NET_ADMIN
    ports:
      - "50051:50051"
      - "4010:4010"
    networks:
      network1:
        ipv4_address: 192.168.1.10

  wait-for-server:
    image: busybox
    depends_on:
      - server
    networks:
      network1:
        ipv4_address: 192.168.1.20
    command: sh -c "sleep 10"

  node1:
    build: .
    entrypoint: ["/bin/sh", "-c", "/app/setup_tc.sh && python3 run_node.py 192.168.1.10:50051"]
    cap_add:
      - NET_ADMIN
    depends_on:
      - wait-for-server
    networks:
      network1:
        ipv4_address: 192.168.1.11

  node2:
    build: .
    entrypoint: ["/bin/sh", "-c", "/app/setup_tc.sh && python3 run_node.py 192.168.1.10:50051"]
    cap_add:
      - NET_ADMIN
    depends_on:
      - wait-for-server
    networks:
      network1:
        ipv4_address: 192.168.1.12

  node3:
    build: .
    entrypoint: ["/bin/sh", "-c", "/app/setup_tc.sh && python3 run_node.py 192.168.1.10:50051"]
    cap_add:
      - NET_ADMIN
    depends_on:
      - wait-for-server
    networks:
      network1:
        ipv4_address: 192.168.1.13

networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
