# Success
REGISTER_SUCCESS = 201
INFERENCE_ACCEPTED = 202
NODE_UPDATE_SUCCESS = 203
NODE_READY_INFORM_SUCCESS = 204
INFERENCE_END_ACCEPTED = 205

# Client error
TENSOR_SHAPE_MISMATCH = 401
IP_ALREADY_REGISTERED = 402
BAD_REQUEST = 403

# Server error
SERVER_ERROR = 501
NO_MORE_MODEL_PARTS_TO_ASSIGN = 502
NODE_UPDATE_ERROR = 503

status = {
    201: 'REGISTER_SUCCESS', 
    202: 'INFERENCE ACCEPTED',
    203: 'NODE UPDATE SUCCESS',
    204: 'NODE READY SUCCESS',
    205: 'INFERENCE END ACCEPTED',

    401: 'TENSOR SHAPE MISMATCH',

    501: 'SERVER ERROR',
    502: 'NO MORE MODEL PARTS TO ASSIGN',
    503: 'NODE UPDATE ERROR'
}